# -*- coding: utf-8 -*-
"""Fundamental python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xAiEta1It3H4z2_WWVOBAnPbeTHCr6ob
"""

x=0
print(x)
x = 100
print (x)
x = -10
x = 123456789
print(x)
x = 2500000000000000000000000000000000234
print(x)

"""Integer - integer can be binary, octal, and hexadecimal values."""

b = 0b1010110000 # binary
print(b)
o = 0o12 # octal
print(o)
h = 0x12 #hexadecimal
print(h)

"""in python, floating point numbers (float) are positive and negatice real numbers with a fractinal part denoted by the scientific notation E or e, e.g. 1234.56, 3.142, -1.55,0.23

"""

x=1234.56
print(x)
f=5e-5
print(f)

# complex number
x = 10+3j
print(x)

"""how to find the type of the variable"""

x=45
print(type(x))

#Use the float() function to convert string, int to float.
x = '123'
print(type(x))
y = float(x)
print(y)
print(type(y))

"""boolean - the python boolean type is one of python's built-in data types. it's used to represent the truth."""

a=1
b=2
c=a>b
print(c)
print(type(c))

"""type casting is implicit int to float casting takes place when any arithmeric operation on int and float operation"""

a = 10 # int object
b = 10.5 # float object
x = a+b
print(x)

"""explicit type casting"""

a = int(10.5) #converts a float object to int
print (a)
a = int (2*3.14) #expression results float, is converted to int
print (a)
print(type(a) )
print (int(False))

"""String to integer the int() function returns an integer from a string object, only if it contains a valid integer"""

a = int ("100")
print (a)
print (type(a))
a = ("10"+"01")
print(a)
print(type(a))
a = int("10"+"02")
print (a)
print(type(a))

"""Use the float() function to vonvert string, int to float"""

f=float('5.5')
print(f) # output 5.5

f=float(5)
print(f) # output 5.0

"""String is collection of characters."""

print ("Hello")

"""String length"""

Dept = "Engin earing"
print(len(Dept))

"""check string(in keyword) to check particular pattern or character is present in the string. we can use in keyword."""

student="I am doing Bio-Technology"
print ("Bio" in student)

"""Not in the string"""

student="I am doing Bio-Technology"
print ("Gio" in student)

"""String Slicing we can extract range of character by using the slice."""

student="I am doing Bio-Technology"
print (student[0:5])

"""negative indexing"""

print (student[-1:])
print (student[-2:])
print (student[-10:])

"""Modify String upper Case
Lower case
Romove Whitespace
"""

name = "Bana Singh"
print(name.upper())
print(name.lower())
name = "     Bana        Singh      "
print(name.strip())

"""Replace String"""

name = "Bana Singh"
print(name.replace("Bana","Dana"))

"""Working with input and output functions python output we use"""

print("Hello World")
a=2
print(a)
print ("The value of a is",a)
b=3
print("The value of a is",a,"the value of b is",b)

"""Python input in python, Input() funciton is used to accept data as input at run time."""

city = input("Enter your city:")
print ("I am from",city)

x = int(input("Enter Number"))
result=(pow(x,2))
print("The square if number =", result)
result=pow(x,3)
print("the cube if number = ",result)

name = input("Enter your name:")
print ("My Name is ",name)
character = "h"
n= name.count(character)
print(n)

import math
a = int(input("Enter Number a : "))
b = int(input("Enter Number b : "))
x=a+b
y=a-b
print(math.sqrt(x))
print(math.pow(x,y))
print(math.exp(x))
print(math.ceil(x))
print(math.floor(x))
print(math.trunc(x))

"""looping statement"""

Num =3
if(Num<0):
  print("Number is Positive")

"""if else"""

Num = int(input("Enter Number : "))
if(Num<0):
  print("Number is negative")
elif(Num==0):
  print("Number is zero")
else:
  print("Number is positive")

"""nestet if"""

x = 30
y = 10
if x>=y:
  print("x is greater than or equals to y ")
  if x == y:
    print("x is equals to y")
  else:
    print("x is greater than y")
else:
    print("x is less than y")

"""While test_expression :

Body of while
"""

n = 10
sum = 0
i = 1
while i <=n:
  sum = sum + i
  i = i+1   # update counter
print("The sum is", sum)

"""example : (Find a list of all numbers from 1 to 25 and calculate the sum of even numbers"""

x = 0
y = 25
z = 1
while z<=y:
  if z %2 ==0:
    x = x +z
  z=z+1
print("output",x)

"""prime number"""

num = int(input("Enter a number: "))

if num <= 1:
    print(num, "is not a prime number")
else:
    is_prime = True

    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print(num, "is a prime number")
    else:
        print(num, "is not a prime number")

"""palindrome"""

num = int(input("Enter a number: "))

original = num
reverse = 0

while num > 0:
    digit = num % 10
    reverse = reverse * 10 + digit
    num = num // 10

if original == reverse:
    print(original, "is a palindrome")
else:
    print(original, "is not a palindrome")

"""odd or even"""

num = int(input("Enter a number: "))
if num %2 == 0:
    print("even",num)
else:
    print("odd",num)

"""Positive or negative"""

num = int(input("Enter a number: "))
if num > 0:
    print("positive",num)
elif num == 0:
    print("zero",num)
else:
    print("negative",num)

"""largest of three number"""

first_value = int(input("Enter a First number: "))
second_value = int(input("Enter a Second number: "))
thrid_value = int(input("Enter a Third number: "))
if first_value>second_value and first_value>thrid_value:
    print("first_value is largest",first_value)
elif second_value>first_value and second_value>thrid_value:
    print("second_value is largest",second_value)
else:
    print("thrid_value is largest",thrid_value)

"""Leap year"""

year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year, "is a leap year")
else:
    print(year, "is not an leap year")

"""Write a program to check if a character is a vowel or constant"""

vowels = ['a', 'e', 'i', 'o', 'u']
character = input("Enter a character: ")

if character.lower() in vowels:
    print(character, "is a vowel")
else:
    print(character, "is a consonant")

mark = int(input("Enter your mark: "))

if mark >= 90:
  print("Grade A")
elif mark >= 80 and mark < 90:
  print("Grade B")
elif mark >= 70 and mark < 80:
  print("Grade C")
elif mark >= 60 and mark < 70:
  print("Grade D")
elif mark >= 50 and mark < 60:
  print("Grade E")
else:
  print("Grade F")

"""print pyramid"""

rows = int(input("Enter the number of rows: "))

i = 1

while i <= rows:
    # Print leading spaces
    space = rows - i
    while space > 0:
        print(" ", end="")
        space -= 1

    # Print the row number
    j = 1
    while j <= i:
        print(i, end=" ")
        j += 1

    print()
    i += 1

"""floyds triangle"""

rows = int(input("Enter the number of rows: "))

i = 1
inc =1
while i <= rows:
    space = rows - i
    while space > 0:
        print(" ", end="")
        space -= 1
    j = 1
    while j <= i:
        print(inc, end=" ")
        j += 1
        inc += 1
    print()
    i += 1

"""List"""

Games=['cricket','Hockey','Tennis']

print(Games)

print(len(Games))

Games.append('Football')

print(Games)

print("The first element in the list:",Games[-1])

print("The first three elements :",Games[1:3])

"""remove elements"""

Games.remove('Football')
print(Games)

for x in Games:
  print(x)

Games.sort()
print(Games)

Games = ['Cricket','Hockey','Football','Tennis']
Games.sort()
print(Games)

Games.sort(reverse=True)
print(Games)

L1=Games.copy()
L1.sort()
L2=Games+L1
print(L2)

L1=[1,2,3,4]
L1.sort(reverse=True)
print(L1)

L1=[1,2,3,4]
L2=['One','Two','Three','Four']
L3=L1+L2
print(L3)

L3=L1.append("Five")

print(L1)

"""Create a list of 10 integer numbers and print the first and last elements.
Print the first 5 elements i L1 and preint the next 5 elements in the L2. Append both the list
"""

list1 = [1,2,3,4,5,6,7,8,9,10]
print("The 1st element:",list1[0])
print("The last element:",list1[-1])
L1 = list1[:5]
L2 = list1[5:]
print(L1)
print(L2)
L3 = L1 + L2
print(L3)

numb=[10,20,30,40]
total = sum(numb)
len(numb)
average = total/len(numb)
print(total)
print(average)

print(max(numb))
print(min(numb))

L1=[1,2,3,4]
Product=1
for x in L1:
  Product *=x
  print(f"product:{Product}")

"""Tuples"""

print(t1[0])
print(t2[0])

print(t1[-1])
print(t2[-1])