# -*- coding: utf-8 -*-
"""Fundamental of python 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-E_mLdhYSvLzpoIcAPo6BueD6yykxJw
"""

t1=(1,2,3)
t2=("apple","banana","figs")

t3=list(t2)
t3.append('lemon')
print("List",t3)
t2 = tuple(t3)
print("Tuple",t2)

"""Create"""

a=(1,2,3)
b=(4,5,6)
c=(7,8,9)
combined =a+b+c
print(combined)

"""tuple slicing"""

sliced=combined[3:6]
print(sliced)

reverse_item = combined[::-1]
print(reverse_item)

T1= ("Rohit,""Kohli","Dawan")
T2= ("Kuldip","Bumrah","Pandya")
T=T1+T2
print(T)

"""Set"""

Fruits={"Apple","banana","Figs","banana","Apple"}
print(Fruits)
print(len(Fruits))

data=set()
if not data:
  print("The Set is empty")
else:
  print("The Set is Not empty")

set_a={1,2,3,4}
set_b={3,4,5,6}
result = set_a.union(set_b)
print(result)

"""intersection of set"""

set_a={1,2,3,4}
set_b={3,4,5,6}
result = set_a.intersection(set_b)
print(result)

Student={
    "name": "Alice","Age":20,"Marks": 85
}
print(Student)

print(Student["name"])

print(Student["Marks"])
print(Student.get("Marks"))

Student["Marks"]=90
Student["Age"]=21
print(Student)

Courses={
    "Alice": ["Math","Physics","Chemistry"],
    "Bob": ["History","English"]
}

print(Courses.get("Alice"))

dict1={'a':1,'b':2,'c':3}
dict2={'d':4,'e':5,'f':6}
dict1.update(dict2)
print(dict1)

# Dictionary of products with details
products={
    "Laptop": {"Price":75000,"stock":10,"category":"Electronics"},
    "Phone": {"Price":50000,"stock":25,"category":"Electronics"},
    "Shoes": {"Price":2500,"stock":50,"category":"Fashion"},
    "Watch": {"Price":6000,"stock":15,"category":"Accessories"}
}
print("Laptop price",products["Laptop"]["Price"])
print("Shoes stock",products["Shoes"]["stock"])

def greet():
  print("Hello, Welcome to Python")
greet()

def add_numbers(a, b):
    print("Sum =", a + b)

num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

add_numbers(num1, num2)

!pip install numpy

import numpy as np
arr=np.array([1,2,3,4,5,6])
arr